import path from 'path'
import os from 'os'

function getCfg(): string {
  let cfg = path.join(process.env.HOME as string, '.config')
  if (process.env.XDG_CONFIG_HOME && process.env.XDG_CONFIG_HOME !== '') {
    cfg = process.env.XDG_CONFIG_HOME
  }

  return path.join(cfg, 'cliflix', 'cliflix.json')
}

export const Config = {
  localConfigPath: getCfg(),

  activeLanguage: '',
  downloadSave: true,
  downloadPath: path.join(os.homedir(), 'Downloads'),

  outputs: {
    available: [
      'Airplay',
      'Chromecast',
      'DLNA',
      'MPlayer',
      'mpv',
      'VLC',
      'IINA',
      'XBMC',
    ],
    favorites: ['VLC'],
  },
  torrents: {
    limit: 30,
    details: {
      seeders: true,
      leechers: true,
      size: true,
      time: true,
    },
    providers: {
      active: '1337x',
      available: [
        '1337x',
        'ThePirateBay',
        'ExtraTorrent',
        'Rarbg',
        'Torrent9',
        'KickassTorrents',
        'TorrentProject',
        'Torrentz2',
      ],
    },
  },
  prompt: {
    fullscreen: true,
    rows: 10,
  },
  subtitles: {
    limit: 30,
    showDownloads: true,
    opensubtitles: {
      useragent: 'PlayMe v1',
      username: null,
      password: null,
      ssl: true,
    },
    languages: {
      available: [
        'Afrikaans',
        'Albanian',
        'Arabic',
        'Armenian',
        'Asturian',
        'Azerbaijani',
        'Basque',
        'Belarusian',
        'Bengali',
        'Bosnian',
        'Breton',
        'Bulgarian',
        'Burmese',
        'Catalan',
        'Chinese (simplified)',
        'Chinese (traditional)',
        'Chinese bilingual',
        'Croatian',
        'Czech',
        'Danish',
        'Dutch',
        'English',
        'Esperanto',
        'Estonian',
        'Extremaduran',
        'Finnish',
        'French',
        'Galician',
        'Georgian',
        'German',
        'Greek',
        'Hebrew',
        'Hindi',
        'Hungarian',
        'Icelandic',
        'Indonesian',
        'Italian',
        'Japanese',
        'Kannada',
        'Kazakh',
        'Khmer',
        'Korean',
        'Kurdish',
        'Latvian',
        'Lithuanian',
        'Luxembourgish',
        'Macedonian',
        'Malay',
        'Malayalam',
        'Manipuri',
        'Mongolian',
        'Montenegrin',
        'Norwegian',
        'Occitan',
        'Persian',
        'Polish',
        'Portuguese',
        'Portuguese (BR)',
        'Portuguese (MZ)',
        'Romanian',
        'Russian',
        'Serbian',
        'Sinhalese',
        'Slovak',
        'Slovenian',
        'Spanish',
        'Swahili',
        'Swedish',
        'Syriac',
        'Tagalog',
        'Tamil',
        'Telugu',
        'Thai',
        'Turkish',
        'Ukrainian',
        'Urdu',
        'Vietnamese',
      ],
      favorites: [
        'English',
        'French',
        'German',
        'Italian',
        'Japanese',
        'Russian',
        'Spanish',
      ],
    },
  },
}
